FROM ubuntu:focal

# customized buildpack-deps:focal-curl
RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		gcc \
		g++ \
		libomp-dev \
	; \
	rm -rf /var/lib/apt/lists/*
