FROM ubuntu:focal

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		gcc \
		g++ \
		libomp-dev \
		make \
		cmake \
	; \
	rm -rf /var/lib/apt/lists/*
